### ISSUE TITLE
Creating maps and moving between maps is very slow

### ISSUE THREAD

**Issue by corinnaj** [roc-and-roll/roc-and-roll#186]
On localhost (in firefox) it takes about 10 seconds to move to a different map and even longer to create a new one.There is no indication that anything is happening during that time.

**Comment by cmfcmf** [comment]
Yeah, I noticed this as well :( I'll look into it.

**Comment by cmfcmf** [comment]
Well... :D It looks like Zod state validation was the culprit. In development, we validated the full state on every state update, which can take >1 second if your state is big. I originally added full state validation on every update to catch errors faster during development. Also, it is worth noting that whenever you move your mouse, the state is updated and thus verified. This results in graphs like these:
![image](https://user-images.githubusercontent.com/2145092/166102904-a3b516ea-9032-4fb5-b994-be679ce1021c.png)

As you can see, the CPU is fully utilized, and the event loop delay gets progressively worse and worse. I then created a flamechart, which also confirms that Zod is indeed the main culprit:
![image](https://user-images.githubusercontent.com/2145092/166102982-a15ed85f-9e72-4865-b337-c19a181d0595.png)

After removing the additional state validation on every update in development, the graphs now look much, much better: 
![image](https://user-images.githubusercontent.com/2145092/166103007-089781a2-8fb7-403d-b2b1-b951a10c7b8f.png)

**Comment by cmfcmf** [comment]
Ah, and if anyone wonders why this only became apparent when moving maps, and not, e.g., when drawing on a map: This is because our optimistic update system works really well (yaay!), and most actions are actually optimistically rendered on the client (hence you don't notice the 10 second delay to and from the server 🙈). Changing maps, however, does not use optimistic actions.
