### ISSUE TITLE
Tokens for tiny creatures should only be a quarter of a tile

### ISSUE THREAD

**Issue by corinnaj** [roc-and-roll/roc-and-roll#194]

**Comment by cmfcmf** [comment]
Similarly, it would be great if small creatures were slightly smaller than a full tile, maybe two thirds the size?

**Comment by cmfcmf** [comment]
I'm thinking that a dropdown would probably be nice: tiny, small, medium, large, huge, gargantuan, gargantuaner, gargantuanest. It feels the most natural to me. WDYT?

**Comment by s4pu** [comment]
What's the shape of a Kraken again? :upside_down_face:

**Comment by cmfcmf** [comment]
> Maybe we can just start with a dropdown and see if anything else is needed later?

Sounds good to me :)
